### ISSUE TITLE
Vim cursorline cuts out on some keywords

### ISSUE THREAD

**Issue by jorgeluiscarrillo** [cocopon/iceberg.vim#78] opened 2020-10-15 21:14 UTC
Environment:
- Fedora 32
- NeoVim (`v0.4.4`)
- Alacritty

If you have a trouble with coloration and are using Vim/Neovim with terminal:
- [x] Does your Vim support full colors? (`:set termguicolors`)
- [x] Does your terminal support full colors? (e.g. Terminal.app doesn't support it)

![output](https://user-images.githubusercontent.com/33134232/96185622-0643a080-0eef-11eb-8f75-d67daa2d8df9.gif)
As shown in the gif, the cursorline goes invisible on certain keywords. Is this intended? If it is, is there any workaround to prevent it from cutting out.

**Comment by cocopon** [comment] 2020-10-20 09:54
That is not intended behavior. Does the problem occur on the other terminal app?

**Comment by jorgeluiscarrillo** [comment] 2020-10-20 23:39
I tried with xfce4-terminal and experienced the same issue. However, I think that it seems to only occur on `.vim` files. I just opened the code for `iceberg.vim` and can reproduce it there whenever `let` is used.

**Comment by cocopon** [comment] 2020-10-21 06:27
- Could you share the .vim file in the screenshot? I'd like to check it in my environment.
- Do you use any extra plugins for `.vim`? (syntax, linting, ...etc.) If you disable all of other plugins, does the problem still occur? Anyway, list of plugins would help me to reproduce a cause.

**Comment by jorgeluiscarrillo** [comment] 2020-10-21 07:38
I did a bit more research and I believe this might be a NeoVim issue neovim/neovim#9019. A few other themes have the same problem.

**Comment by cocopon** [comment] 2020-10-27 23:49
Reproduced the same issue in Neovim, and works fine in Vim. It seems to be caused by Neovim issue as you said.

Neovim:
<img width="682" alt="nvim" src="https://user-images.githubusercontent.com/602961/97373756-03d34480-18fa-11eb-8a90-5a58ceefc037.png">
```
:version
NVIM v0.5.0-nightly
```

Vim:
<img width="682" alt="vim" src="https://user-images.githubusercontent.com/602961/97373764-09c92580-18fa-11eb-9b26-31692a9bdba1.png"> 
```
:version
VIM - Vi IMproved 8.2 (2019 Dec 12, compiled May 19 2020 22:09:59)
macOS version
Included patches: 1-800
```

**Comment by cocopon** [comment] 2020-12-25 06:50
This problem should be fixed by Neovim. Let's wait for the future release...

**Closed by cocopon** 2020-12-25 06:50 UTC
